# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'
## => Site Settings
##############################
text_skin: default
highlight_theme: default
url     : http://robofuture.net.cn
baseurl : /
title   : Robofuture RM Team
description: 浙纺 Robofuture 团队成员用于分享自学经历的博客站


## => Language and Timezone
##############################
lang: zh # the language of your site, default as "en"
timezone: Asia/Shanghai 


## => Author and Social
##############################
author:
  type      : organization
  name      : Robofuture
  url       : https://github.com/Robofuture
  avatar    : /assets/apple-touch-icon.png # 头像
  bio       : Robofuture RM Team
  email     :
  # facebook  : # "user_name" the last part of your profile url, e.g. https://www.facebook.com/user_name
  # twitter   : # "user_name" the last part of your profile url, e.g. https://twitter.com/user_name
  # weibo     : # "user_id"   the last part of your profile url, e.g. https://www.weibo.com/user_id/profile?...
  # googleplus: # "user_id"   the last part of your profile url, e.g. https://plus.google.com/u/0/user_id
  # telegram  : # "user_name" the last part of your profile url, e.g. https://t.me/user_name
  # medium    : # "user_name" the last part of your profile url, e.g. https://medium.com/user_name
  # zhihu     : # "user_name" the last part of your profile url, e.g. https://www.zhihu.com/people/user_name
  # douban    : # "user_name" the last part of your profile url, e.g. https://www.douban.com/people/user_name
  # linkedin  : # "user_name" the last part of your profile url, e.g. https://www.linkedin.com/in/user_name
  # github    : # "user_name" the last part of your profile url, e.g. https://github.com/user_name
  # npm       : # "user_name" the last part of your profile url, e.g. https://www.npmjs.com/~user_name


## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: Robofuture-RM/Robofutue-RM.github.io
repository_tree: master


## => Paths
##############################
paths:
  root    : # title link url, "/" (default)
  home    : # home layout url, "/" (default)
  archive : # "/archive.html" (default)
  rss     : # "/feed.xml" (default)


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## license
license: CC-BY-NC-4.0 # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0"

## TOC
toc:
  selectors: # "h1,h2,h3" (default)


## => Markdown Enhancements
##############################
## Mathjax
mathjax: true # false (default), true
mathjax_autoNumber: true # false (default), true

## Mermaid
mermaid: true # false (default), true

## Chart
chart: true # false (default), true


## => Paginate
##############################
paginate: 8
paginate_path: /page:num # don't change this unless for special need


## => Sources
##############################
sources: bootcdn # bootcdn (default), unpkg


## => Sharing
##############################
sharing:
  provider: addtoany # false (default), "addtoany", "addthis", "custom"

  ## AddThis
  addthis:
    id: # AddThis pubid, e.g. ra-5xxxxxxxxxxx


## => Comments
##############################
comments:
  provider: gitalk # false (default), "disqus", "gitalk", "valine", "custom"

  ## Disqus
  disqus:
    shortname: # the Disqus shortname for the site

  ## Gitalk
  # please refer to https://github.com/gitalk/gitalk for more info.
  gitalk:
    clientID    : 29c97530b8da656cbfc5 # GitHub Application Client ID
    clientSecret: f970ee77e112b3713e567e5bf74a91b3571e188c # GitHub Application Client Secret
    repository  : Robofuture-RM.github.io # GitHub repo
    owner       : Robofuture-RM # GitHub repo owner
    admin: # GitHub repo owner and collaborators, only these guys can initialize GitHub issues, IT IS A LIST.
      - Robofuture-RM # - your GitHub Id

  ## Valine
  # please refer to https://valine.js.org/en/ for more info.
  valine:
    app_id      : # LeanCloud App id
    app_key     : # LeanCloud App key
    placeholder : # Prompt information
    visitor     : # false (default)
    meta        : # "[nick, mail, link]" (default) nickname, E-mail, Personal-site


## => Pageview
##############################
pageview:
  provider: false # false (default), "leancloud", "custom"

  ## Leancloud
  leancloud:
    app_id    : # LeanCloud App id
    app_key   : # LeanCloud App key
    app_class : # LeanCloud App class


## => Search
##############################
search:
  provider: default # "default" (default), false, "google", "custom"

  ## Google Custom Search Engine
  google:
    custom_search_engine_id: # Google Custom Search Engine ID


## => Analytics
##############################
analytics:
  provider: false # false (default), "google", "custom"

  ## Google Analytics
  google:
    tracking_id : # Google Analytics id for the site
    anonymize_ip: false # Anonymize IP tracking for Analytics


## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : date

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md


defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true

## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
